### ISSUE TITLE
Not compatible with ember-source

### ISSUE THREAD

**Issue by halfdan** [roofstock/ember-cli-data-export#11]
Ember is now distributed via npm and no longer exists in bower_components. 

```
Cannot find module '/Users/fabian/Projects/.../bower_components/ember/ember-template-compiler.js'
Error: Cannot find module '/Users/fabian/Projects/.../bower_components/ember/ember-template-compiler.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.htmlbarsOptions (/Users/fabian/Projects/.../node_modules/ember-cli-data-export/node_modules/ember-cli-htmlbars/ember-addon-main.js:99:25)
```

Looks like ember-cli-htmlbars needs an update.

**Comment by austexcn** [comment]
@matt-roofstock can you bump the version number so I can get the version with these changes from npm
