### ISSUE TITLE
Ember test command with ember-cli@2.13.1 not working

### ISSUE THREAD

**Issue by Gorzas** [roofstock/ember-cli-data-export#15]
I'm trying to test the addon because I want to suggest some changes to library but it seems that I can't. I'm using ember-cli@2.13.1 and, when I use the command `ember test`, it shows the following error message:

```
Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-addon'
Error: Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-addon'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/joseda/git/ember-cli-data-export/ember-cli-build.js:2:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```
Does anybody have any clue about what's happening? Can we upgrade the addon to be compatible with the latest version of ember-cli?

**Comment by Gorzas** [comment]
It was my fault. I was using a not updated version of the addon :(. Sorry.
